/* eslint-disable max-lines -- 公开协议允许列表集中维护，防止分散配置遗漏授权边界。 */
/** 显式公布的公网能力允许列表；新增内部方法不会自动扩大远控权限。 */
export const RCS_SERVICE_MANIFEST: Record<
  string,
  { methods: readonly string[]; events: readonly string[] }
> = {
  file: {
    methods: [
      "searchWorkspaceFiles",
      "readdir",
      "stat",
      "checkFilesExist",
      "resolvePath",
      "readTextFile",
      "readMediaPreview",
      "readFileRange",
      "readBinaryPreview",
      "listWorkspaceFilesLength",
      "listWorkspaceFilesRange",
      "readWorkspaceFileSearchIgnore",
      "applyWorkspaceFileSearchIgnoreTransform",
      "writeWorkspaceFileSearchIgnore",
      "writeTextFile",
    ],
    events: [],
  },
  git: {
    methods: [
      "getRepositorySummary",
      "getWorkspaceRepositoryInfo",
      "getLocalBranches",
      "getCommitGraph",
      "switchBranch",
      "createBranchAndSwitch",
      "getChanges",
      "getIgnoredPaths",
      "getDiff",
      "getBranchComparison",
      "stagePaths",
      "unstagePaths",
      "discardPaths",
      "generateCommitMessage",
      "commit",
      "push",
      "getIdentity",
      "refresh",
    ],
    events: [],
  },
  "git-checkpoint": {
    methods: [
      "createCheckpoint",
      "diffCheckpoints",
      "restoreBetweenCheckpoints",
      "deleteCheckpoint",
    ],
    events: [],
  },
  system: {
    methods: ["info", "listIntegratedTerminalShells"],
    events: [],
  },
  terminal: {
    methods: ["create", "write", "resize", "dispose", "list", "attach", "detach"],
    events: ["onDynamicData", "onDynamicExit", "onDynamicReplayData"],
  },
  setting: {
    methods: ["get", "update"],
    events: [],
  },
  "zcode-task": {
    methods: [
      "initialize",
      "createTask",
      "sendPrompt",
      "deliverSessionMessage",
      "sendSessionMessageDeliveryResult",
      "enqueueTaskCommand",
      "promoteTaskCommand",
      "cancelTaskCommand",
      "stopGeneration",
      "compactSession",
      "goalSession",
      "respondPermission",
      "respondElicitation",
      "closeTask",
      "resumeTask",
      "listTasks",
      "listPinnedTaskIds",
      "listPinnedTasks",
      "listDeletedTaskIds",
      "listTaskList",
      "createTaskGroup",
      "renameTaskGroup",
      "updateTaskGroupColor",
      "deleteTaskGroup",
      "listGroupedTaskViewStructure",
      "applyGroupedTaskViewOrder",
      "listArchivedTasks",
      "archiveStaleTasks",
      "archiveWorkspaceTasks",
      "getTaskSnapshot",
      "getTaskSnapshotWithEtag",
      "getTaskSnapshotBody",
      "getTaskSnapshotRef",
      "getTaskSnapshotToolCallsSlice",
      "getTaskMeta",
      "getTaskConfigOptions",
      "getTaskModelSelection",
      "setAssistantMessageFeedback",
      "setMode",
      "setConfigOption",
      "setModel",
      "setAutomationSessionConfig",
      "getModelTrajectory",
      "getTaskTokenUsage",
      "deleteTask",
      "deleteArchivedTask",
      "deleteArchivedTasks",
      "renameTask",
      "setTaskPinned",
      "setTaskUnread",
      "archiveTask",
      "unarchiveTask",
      "branchTaskFromPrompt",
    ],
    events: [
      "onDynamicStreamEvent",
      "onDynamicTaskTerminalOutcome",
      "onDynamicTaskReady",
      "onDynamicTaskEvent",
      "onDynamicWorkspaceEvent",
    ],
  },
  "window-controller": {
    methods: [
      "deleteArchivedTask",
      "deleteArchivedTasks",
      "listTaskList",
      "mutateTask",
      "subscribeControllerV4",
      "resyncControllerV4",
      "unsubscribeControllerV4",
    ],
    events: ["onDynamicControllerFrame"],
  },
  "zcode-agent": {
    methods: [
      "prepareStorage",
      "getStorageStartupState",
      "initialize",
      "getWorkspaceRuntimeIdentity",
      "createSession",
      "resumeSession",
      "listSessions",
      "listSessionSubagents",
      "getTaskTokenUsage",
      "readSession",
      "readSessionMessages",
      "readSessionDebug",
      "readSessionEvents",
      "readWorkspacePresentation",
      "grantWorkspaceHookTrust",
      "listMcpServerStatuses",
      "listPlugins",
      "getPluginReferenceCatalog",
      "getSkillReferenceCatalog",
      "listSavedWorkflows",
      "getSavedWorkflow",
      "updateSavedWorkflowMeta",
      "deleteSavedWorkflow",
      "listSavedWorkflowRuns",
      "moveSavedWorkflow",
      "resolveSuggestedPluginReference",
      "getPluginsOverview",
      "addPluginMarketplace",
      "removePluginMarketplace",
      "updatePluginMarketplace",
      "installPlugin",
      "cancelPluginOperation",
      "uninstallPlugin",
      "updatePlugin",
      "restoreBuiltinPlugin",
      "configurePlugin",
      "resetPluginConfig",
      "validatePlugin",
      "describePlugin",
      "setPluginEnabled",
      "listAutomations",
      "createAutomation",
      "updateAutomation",
      "deleteAutomation",
      "setAutomationEnabled",
      "restartAutomation",
      "runAutomationNow",
      "listAutomationRuns",
      "deleteAutomationRun",
      "generateWorkspaceText",
      "testModelConnectivity",
      "sendPrompt",
      "compactSession",
      "reviewProjectMemory",
      "workspaceMemory",
      "readProjectMemoryReview",
      "cancelProjectMemoryReview",
      "goalSession",
      "closeSession",
      "setModel",
      "setThoughtLevel",
      "setMode",
      "respondSessionRuntimePreferences",
      "helloConversationV4",
      "initializeConversationV4",
      "subscribeConversationV4",
      "resyncConversationV4",
      "unsubscribeConversationV4",
      "conversationRowsRangeV4",
      "conversationPlansV4",
      "conversationWorkflowRunEventsV4",
      "conversationWorkflowRunsV4",
      "conversationWorkflowRunArtifactsV4",
      "conversationWorkflowRunArtifactDataV4",
      "conversationWorkflowRunArtifactReadV4",
      "conversationWorkflowRunWorkspaceV4",
      "conversationWorkflowRunNodeResultV4",
      "backgroundBashOutputV4",
      "conversationFileChangesV4",
      "conversationFileRewindPreviewV4",
      "sendConversationCommandV4",
      "queryConversationCommandsV4",
      "attachmentBeginV4",
      "attachmentChunkV4",
      "attachmentCommitV4",
      "attachmentAbortV4",
      "attachmentPreviewSourceV4",
      "attachmentReadV4",
      "conversationAttachmentReadV4",
      "conversationAttachmentStatV4",
      "subscribeSessionsIndexV4",
      "resyncSessionsIndexV4",
      "unsubscribeSessionsIndexV4",
      "subscribeWorkspaceConfigV4",
      "resyncWorkspaceConfigV4",
      "unsubscribeWorkspaceConfigV4",
    ],
    events: [
      "onDynamicStorageStartupState",
      "onDynamicPluginOperationProgress",
      "onDynamicSessionEvent",
      "onDynamicConversationFrame",
      "onDynamicSessionsIndexFrame",
      "onDynamicWorkspaceConfigFrame",
      "onAgentRuntimeRestarted",
      "onAgentRuntimeLifecycle",
    ],
  },
  "zcode-session": {
    methods: [
      "initializeWorkspace",
      "getWorkspaceRuntimeIdentity",
      "readWorkspacePresentation",
      "createSession",
      "resumeSession",
      "listSessions",
      "readSession",
      "readSessionMessages",
      "readSessionEvents",
      "promoteDeferredDraftSession",
      "closeSession",
      "closeDeferredDraftSession",
      "setModel",
      "setThoughtLevel",
      "setMode",
    ],
    events: [],
  },
  "model-selection": {
    methods: ["getView"],
    events: ["onDidChange"],
  },
  "provider-settings": {
    methods: [
      "getView",
      "refresh",
      "createPersonalProvider",
      "savePersonalProviderOverlay",
      "deletePersonalProvider",
      "reorderPersonalProviders",
      "reorderPersonalModels",
      "addPersonalModel",
      "renamePersonalModel",
      "deletePersonalModel",
      "savePersonalModelDraft",
      "setPersonalModelEnabled",
      "discoverModels",
      "setPersonalModelFastMode",
      "testModelConnectivity",
    ],
    events: ["onDidChange"],
  },
  "image-generation": {
    methods: ["getSettings", "saveSettings", "listModels", "validate"],
    events: [],
  },
  skills: {
    methods: [
      "list",
      "setEnabled",
      "buildPromptContext",
      "copyToCommon",
      "removeFromCommon",
      "deleteSkill",
    ],
    events: [],
  },
  plugins: {
    methods: [
      "getOverview",
      "addMarketplace",
      "removeMarketplace",
      "updateMarketplace",
      "installPlugin",
      "uninstallPlugin",
      "setPluginEnabled",
    ],
    events: [],
  },
  "plugin-management": {
    methods: [
      "listPlugins",
      "getPluginReferenceCatalog",
      "resolveSuggestedPluginReference",
      "getPluginsOverview",
      "addPluginMarketplace",
      "removePluginMarketplace",
      "updatePluginMarketplace",
      "installPlugin",
      "cancelPluginOperation",
      "uninstallPlugin",
      "updatePlugin",
      "restoreBuiltinPlugin",
      "configurePlugin",
      "resetPluginConfig",
      "validatePlugin",
      "describePlugin",
      "setPluginEnabled",
    ],
    events: ["onDynamicPluginOperationProgress"],
  },
  subagents: {
    methods: [
      "list",
      "setEnabled",
      "setBuiltInModelOverride",
      "setPluginAgentModelOverride",
      "createAgent",
      "updateAgent",
      "deleteAgent",
    ],
    events: [],
  },
  commands: {
    methods: [
      "list",
      "writeCommandFile",
      "updateCommandFile",
      "deleteCommandFile",
      "setCommandEnabled",
    ],
    events: [],
  },
  hooks: {
    methods: ["loadHooks", "saveHooks", "grantWorkspaceHookTrust"],
    events: [],
  },
  memory: {
    methods: ["listProjectMemories", "readProjectMemoryFile"],
    events: [],
  },
  "usage-stats": {
    methods: [
      "getAppUsageSnapshot",
      "getCodingPlanUsageSnapshot",
      "getCodingPlanResetStatus",
      "requestCodingPlanResetOpportunity",
      "useCodingPlanReset",
      "markCodingPlanResetHistoryRead",
      "getSnapshot",
      "getEntitlementSnapshot",
    ],
    events: [],
  },
  "coding-plan-subscription": { methods: ["getDynamicWorkflowClientConfig"], events: [] },
  "client-scenes": {
    methods: ["list"],
    events: [],
  },
  "file-watcher": {
    methods: ["watch", "unwatch"],
    events: ["onDynamicChange"],
  },
  "media-preview": {
    methods: ["prepare", "refreshPlaybackUrl", "release"],
    events: [],
  },
  credential: {
    methods: [],
    events: [],
  },
  broadcast: {
    methods: ["send", "sendWithAcknowledgements"],
    events: ["onMessage"],
  },
};
